// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMjwGLmSzw6YLFe651CReOI8uv7a1DIuk',
    appId: '1:231958812688:web:98cc8207984a5e1e4bd295',
    messagingSenderId: '231958812688',
    projectId: 'chat-29c58',
    authDomain: 'chat-29c58.firebaseapp.com',
    storageBucket: 'chat-29c58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkoL2hR1L5qqRHt13n2TNBhNa24KiX_BQ',
    appId: '1:231958812688:android:436500b0883e7f854bd295',
    messagingSenderId: '231958812688',
    projectId: 'chat-29c58',
    storageBucket: 'chat-29c58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1S8wc06bSdb_F8a1SzNsSWuv-yt83K1Y',
    appId: '1:231958812688:ios:51841581ae3991554bd295',
    messagingSenderId: '231958812688',
    projectId: 'chat-29c58',
    storageBucket: 'chat-29c58.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1S8wc06bSdb_F8a1SzNsSWuv-yt83K1Y',
    appId: '1:231958812688:ios:51841581ae3991554bd295',
    messagingSenderId: '231958812688',
    projectId: 'chat-29c58',
    storageBucket: 'chat-29c58.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMjwGLmSzw6YLFe651CReOI8uv7a1DIuk',
    appId: '1:231958812688:web:b59ce6050118fa3f4bd295',
    messagingSenderId: '231958812688',
    projectId: 'chat-29c58',
    authDomain: 'chat-29c58.firebaseapp.com',
    storageBucket: 'chat-29c58.appspot.com',
  );
}
